/** A/B counts are frozen (docs/stage5b-api-inventory.md). C is Stage 5-C only. */

export const IMPLEMENTED_A = [
  "_strCom/601",
  "_strCom/800",
  "_strCom/801",
  "_strCom/802",
  "_com/1",
  "_com/400",
  "_com/403",
  "_com/3629",
  "GetSysInfo",
  "TimerStart",
  "TimerStop",
  "_clearScr",
  "_drawRect",
  "_drawText",
  "_dispUp",
  "EffSetCon",
  "Exit",
  "_t",
  "_gc",
  "_mr_entry",
  "_mr_param",
  "dealevent",
  "dealtimer",
  "suspend",
  "resume",
  "mr_event",
  "mr_timer",
  "advance",
  "step",
] as const;

export const IMPLEMENTED_B = [
  "_strCom/602",
  "file.open",
  "file.close",
  "file.state",
  "file.readAll",
  "f.read",
  "f.seek",
  "f.write",
  "sys.getuptime",
  "sys.getFileLen",
  "sys.getFileInfo",
  "GetDatetime",
  "_rand",
  "_mod",
  "_and",
  "_or",
  "_xor",
  "_not",
  "_drawLine",
  "_drawPoint",
  "_dispUpEx",
  "_com/100",
  "_com/101",
  "_com/102",
  "_com/401",
  "_com/406",
] as const;

export const IMPLEMENTED_C = [
  "string.len",
  "string.sub",
  "string.pack",
  "string.unpack",
  "string.subV",
  "table.rawGet",
  "table.getn",
  "_setTab",
  "SaveTable",
  "LoadTable",
  "_runFile",
  "_strCom/300",
  "_strCom/500",
  "_strCom/501",
  "_strCom/502",
  "BitmapShow",
  "SpriteDraw",
  "TileDraw",
  "metamethod/__index",
  "metamethod/__newindex",
  "mr_table/0",
  "mr_table/14",
  "mr_table/125",
  "mr_table/130/7",
  "mr_table/38/0x4c6",
  "mr_table/33/mr_getTime",
  // Only the observed guest sprintf subset consisting of
  // literal bytes and %d is currently implemented.
  "mr_table/17/sprintf/%d",
  // 128-byte guest data slot. Populated from current pack identity
  // (MythroadRuntime.packName) with rxgj arm_ext_set_pack_table_name
  // memset+snprintf semantics. Not a function ABI / filesystem API.
  "mr_table/100/pack_filename",
] as const;
