/** Implemented Stage 5-B surface. Counts must match docs/stage5b-api-inventory.md. */

export const IMPLEMENTED_A = [
  "_strCom/601",
  "_strCom/800",
  "_strCom/801",
  "_strCom/802",
  "_com/1",
  "_com/400",
  "_com/403",
  "_com/3629",
  "GetSysInfo",
  "TimerStart",
  "TimerStop",
  "_clearScr",
  "_drawRect",
  "_drawText",
  "_dispUp",
  "EffSetCon",
  "Exit",
  "_t",
  "_gc",
  "_mr_entry",
  "_mr_param",
  "dealevent",
  "dealtimer",
  "suspend",
  "resume",
  "mr_event",
  "mr_timer",
  "advance",
  "step",
] as const;

export const IMPLEMENTED_B = [
  "_strCom/602",
  "file.open",
  "file.close",
  "file.state",
  "file.readAll",
  "f.read",
  "f.seek",
  "f.write",
  "sys.getuptime",
  "sys.getFileLen",
  "sys.getFileInfo",
  "GetDatetime",
  "_rand",
  "_mod",
  "_and",
  "_or",
  "_xor",
  "_not",
  "_drawLine",
  "_drawPoint",
  "_dispUpEx",
  "_com/100",
  "_com/101",
  "_com/102",
  "_com/401",
  "_com/406",
] as const;
